### ISSUE TITLE
Error startup example

### ISSUE THREAD

**Issue by matteomartinelli** [alexhultman/node-lws#1]
While starting the example I get this:
```
> node server_lws.js
module.js:435
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 14.
    at Error (native)
    at Object.Module._extensions..node (module.js:435:18)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/crmhero-git/websocket/node_modules/lws/lws.js:1:80)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
```

How can I solve?

**Comment by alexhultman** [comment]
Why hello there.

You are using the pre-compiled Linux binary. This binary is compiled against nodejs 0.12 (module version 14) and you have nodejs 4.x (module version 46): https://nodejs.org/en/download/releases/

I need to re-compile it for Node 4.x when I get the time to do so. Currently I have 0.12, will update to 4.x.

**Comment by matteomartinelli** [comment]
Hi Alex,
thank you for you answer! I'm looking for an high number of connections and I found your post regarding 500k connection with 2gb ram that is quite powerful

**Comment by alexhultman** [comment]
OS X and Linux binaries are now compiled for Node 4.x. Keep in mind this project is very unfinished.
